apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - default:
      cpu: 600m
      memory: 1Gi
    defaultRequest:
      cpu: 10m
      memory: 50Mi
    max:
      cpu: 1
      memory: 2Gi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container
    
