apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: istio-grafana
    chart: grafana-1.0.1
    heritage: Tiller
    release: RELEASE-NAME
  name: istio-grafana-post-install
  namespace: istio-system
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: istio-grafana
        job-name: istio-grafana-post-install
        release: RELEASE-NAME
      name: istio-grafana-post-install
    spec:
      containers:
      - command:
        - /bin/bash
        - /tmp/grafana/run.sh
        - /tmp/grafana/custom-resources.yaml
        image: quay.io/coreos/hyperkube:v1.7.6_coreos.0
        imagePullPolicy: IfNotPresent
        name: hyperkube
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/grafana
          name: tmp-configmap-grafana
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-grafana-post-install-account
      serviceAccountName: istio-grafana-post-install-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: istio-grafana-custom-resources
        name: tmp-configmap-grafana
